ALTER TABLE events ADD COLUMN artist TEXT NOT NULL;
ALTER TABLE events ADD COLUMN start_date TIMESTAMP NOT NULL;

ALTER TABLE events DROP COLUMN slug;
ALTER TABLE events DROP COLUMN flyer;
ALTER TABLE events DROP COLUMN start;
ALTER TABLE events DROP COLUMN end;
ALTER TABLE events DROP COLUMN capacity;
ALTER TABLE events DROP COLUMN guest_list_id;
