ALTER TABLE events DROP COLUMN artist;
ALTER TABLE events DROP COLUMN start_date;

ALTER TABLE events ADD COLUMN slug TEXT NOT NULL;
ALTER TABLE events ADD COLUMN flyer TEXT;
ALTER TABLE events ADD COLUMN start TIMESTAMP NOT NULL;
ALTER TABLE events ADD COLUMN end TIMESTAMP;
ALTER TABLE events ADD COLUMN guest_list_id INTEGER;
