CREATE TABLE IF NOT EXISTS flyers (
    id INTEGER PRIMARY KEY NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    rotation INTEGER NOT NULL,
    z_index INTEGER NOT NULL,
    image_url TEXT NOT NULL,
    event_url TEXT,
    event_end TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
