DROP TABLE IF EXISTS events;

CREATE TABLE events (
    id INTEGER PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    flyer TEXT,
    description TEXT NOT NULL,

    start TIMESTAMP NOT NULL,
    end TIMESTAMP,

    capacity INTEGER NOT NULL,
    unlisted BOOLEAN NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS events_slug_unique ON events(slug);
