CREATE TABLE IF NOT EXISTS rsvps (
    id INTEGER PRIMARY KEY NOT NULL,
    event_id INTEGER NOT NULL,
    spot_id INTEGER NOT NULL,
    contribution INTEGER NOT NULL,

    status TEXT NOT NULL,
    session_id INTEGER NOT NULL,
    user_id INTEGER,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checkin_at TIMESTAMP
);
