ALTER TABLE event_flyers ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE event_flyers ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE event_flyers ADD COLUMN image_thumb BLOB NOT NULL DEFAULT X'';
