CREATE TABLE IF NOT EXISTS flyers (
    id INTEGER PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    rotation INTEGER NOT NULL DEFAULT 0,
    image_data BLOB NOT NULL DEFAULT X'',
    image_version INTEGER NOT NULL DEFAULT 1,
    link_url TEXT,
    flyer_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
