[app]
domain = "localhost"
url = "https://localhost:4433"
tz = "America/New_York"
session_expiry_days = 365

[db]
file = "db.sqlite"
seed_data = "config/seed_data.sql"

[net]
http_addr = "[::]:8080"
https_addr = "[::]:4433"

[email]
smtp_addr = "smtp://localhost:1025"
from = "Light and Sound Design <studio@beta.lightandsound.design.local>"

[stripe]
publishable_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
webhook_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[cloudflare]
# Test keys (see https://developers.cloudflare.com/turnstile/troubleshooting/testing)
turnstile_site_key = "1x00000000000000000000BB"
turnstile_secret_key = "1x0000000000000000000000000000000AA"
