[app]
domain = "localhost"
url = "http://localhost:8080"
tz = "America/New_York"
session_cookie_max_age_days = 365

[db]
file = "db.sqlite"
seed_data = "config/seed_data.toml"

[net]
http_addr = "[::]:8080"
https_addr = "[::]:4433"

[email]
smtp_addr = "smtp://localhost:1025"
from = "Light and Sound Design <studio@beta.lightandsound.design>"
