[app]
url = "https://localhost:4433"
tz = "America/New_York"

[db]
file = "db.sqlite"

[net]
http_addr = "[::]:8080"
https_addr = "[::]:4433"

[email]
smtp_addr = "smtp://localhost:1025"
from = "WLSD <studio@lightandsound.design>"
