[app]
domain = "beta.lightandsound.design"
url = "https://beta.lightandsound.design"
tz = "America/New_York"
session_expiry_days = 30

[db]
file = "db.sqlite"

[net]
http_addr = "[::]:80"
https_addr = "[::]:443"

[acme]
domain = "beta.lightandsound.design"
email = "studio@beta.lightandsound.design"
dir = "acme"
prod = true

[email]
smtp_addr = "smtp://email-smtp.us-east-1.amazonaws.com?tls=required"
smtp_username = "$SMTP_USERNAME"
smtp_password = "$SMTP_PASSWORD"
from = "Light and Sound Design <studio@beta.lightandsound.design>"
ratelimit = 10
