[app]
url = "https://wlsd.lightandsound.design"
db = "db.sqlite"

[net]
http_addr = "[::]:80"
https_addr = "[::]:443"

[acme]
domain = "wlsd.lightandsound.design"
email = "studio249@foltz.io"
dir = "acme"
prod = true

[email]
addr = "smtp://localhost:1080"
from = "WLSD <wlsd@foltz.io>"
