[app]
domain = "beta.lightandsound.design"
url = "https://beta.lightandsound.design"
tz = "America/New_York"
session_expiry_days = 30

[db]
file = "db.sqlite"

[net]
http_addr = "[::]:80"
https_addr = "[::]:443"

[acme]
domain = "beta.lightandsound.design"
email = "$EMAIL_FROM"
dir = "acme"
prod = true

[email]
smtp_addr = "smtp://email-smtp.us-east-1.amazonaws.com?tls=required"
smtp_username = "$SMTP_USERNAME"
smtp_password = "$SMTP_PASSWORD"
ratelimit = 10
from = "Light and Sound Design <$EMAIL_FROM>"
newsletter_reply_to = "$EMAIL_NEWSLETTER_REPLY_TO"
contact_to = "$EMAIL_CONTACT_TO"

[stripe]
publishable_key = "$STRIPE_PUBLISHABLE_KEY"
secret_key = "$STRIPE_SECRET_KEY"
webhook_key = "$STRIPE_WEBHOOK_KEY"
