[[users]]
email = "test1@test.com"
first_name = "Test1"
last_name = "Testington"
[[users]]
email = "test2@test.com"
first_name = "Test2"
last_name = "Testington"
[[users]]
email = "test3@test.com"
first_name = "Test3"
last_name = "Testington"
[[users]]
email = "test4@test.com"
first_name = "Test4"
last_name = "Testington"
[[users]]
email = "test5@test.com"
first_name = "Test5"
last_name = "Testington"
[[users]]
email = "test6@test.com"
first_name = "Test6"
last_name = "Testington"
[[users]]
email = "test7@test.com"
first_name = "Test7"
last_name = "Testington"
[[users]]
email = "test8@test.com"
first_name = "Test8"
last_name = "Testington"
[[users]]
email = "test9@test.com"
first_name = "Test9"
last_name = "Testington"
[[users]]
email = "test10@test.com"
first_name = "Test10"
last_name = "Testington"
[[users]]
email = "test11@test.com"
first_name = "Test11"
last_name = "Testington"
[[users]]
email = "test12@test.com"
first_name = "Test12"
last_name = "Testington"
[[users]]
email = "test13@test.com"
first_name = "Test13"
last_name = "Testington"
[[users]]
email = "test14@test.com"
first_name = "Test14"
last_name = "Testington"
[[users]]
email = "test15@test.com"
first_name = "Test15"
last_name = "Testington"
[[users]]
email = "test16@test.com"
first_name = "Test16"
last_name = "Testington"
[[users]]
email = "test17@test.com"
first_name = "Test17"
last_name = "Testington"
[[users]]
email = "test18@test.com"
first_name = "Test18"
last_name = "Testington"
[[users]]
email = "test19@test.com"
first_name = "Test19"
last_name = "Testington"
[[users]]
email = "test20@test.com"
first_name = "Test20"
last_name = "Testington"
[[users]]
email = "test21@test.com"
first_name = "Test21"
last_name = "Testington"
[[users]]
email = "test22@test.com"
first_name = "Test22"
last_name = "Testington"
[[users]]
email = "test23@test.com"
first_name = "Test23"
last_name = "Testington"
[[users]]
email = "test24@test.com"
first_name = "Test24"
last_name = "Testington"
[[users]]
email = "test25@test.com"
first_name = "Test25"
last_name = "Testington"
[[users]]
email = "test26@test.com"
first_name = "Test26"
last_name = "Testington"
[[users]]
email = "test27@test.com"
first_name = "Test27"
last_name = "Testington"
[[users]]
email = "test28@test.com"
first_name = "Test28"
last_name = "Testington"
[[users]]
email = "test29@test.com"
first_name = "Test29"
last_name = "Testington"
[[users]]
email = "test30@test.com"
first_name = "Test30"
last_name = "Testington"
[[users]]
email = "test31@test.com"
first_name = "Test31"
last_name = "Testington"
[[users]]
email = "test32@test.com"
first_name = "Test32"
last_name = "Testington"
[[users]]
email = "test33@test.com"
first_name = "Test33"
last_name = "Testington"
[[users]]
email = "test34@test.com"
first_name = "Test34"
last_name = "Testington"


# Can add manually to cookies store in browser to persist sessions between database resets
[[session_tokens]]
user_id = 1
token = "91acde7529be7cf7"

[[user_roles]]
user_id = 1
role = "admin"
created_at = "2025-04-04T16:03:35"

[[user_roles]]
user_id = 1
role = "writer"
created_at = "2025-04-04T16:03:35"
