[[users]]
email = "test@test.com"
first_name = "Test"
last_name = "Testington"

# Can add manually to cookies store in browser to persist sessions between database resets
[[session_tokens]]
user_id = 1
token = "91acde7529be7cf7"

[[user_roles]]
user_id = 1
role = "admin"
created_at = "2025-04-04T16:03:35"

[[user_roles]]
user_id = 1
role = "writer"
created_at = "2025-04-04T16:03:35"
