name: Release
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: debian-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: deploy
        run: scripts/deploy.sh wlsd.foltz.io
