name: Rollback
on:
  workflow_dispatch: {}

jobs:
  rollback:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ROOT_SSH_PRIVKEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan beta.lightandsound.design > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Rollback
        run: scripts/rollback.sh ec2-user@beta.lightandsound.design
