name: Test
on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  rustfmt:
    name: Format
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check

  prettier:
    name: Format frontend
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run:
          deno install npm:prettier
          deno run -A npm:prettier frontend/templates frontend/styles --check

  clippy:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings

  cross:
    name: Cross-compile
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: install gcc-aarch64-linux-gnu
        run: sudo apt install -y gcc-aarch64-linux-gnu
      - run: cargo build --target aarch64-unknown-linux-gnu
